services:
  - type: web
    name: activitycenter
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug

      - key: APP_KEY

      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: activitycenter-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: activitycenter-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: activitycenter-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: activitycenter-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: activitycenter-db
          property: password

databases:
  - name: activitycenter-db
    plan: free
